name: Nightly Code Analysis

on:
  schedule:
    - cron: '5 12 * * *'  # Runs at 5:35 PM IST (12:05 PM UTC) daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50  # To get enough commit history

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run code analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REPO_NAME: anuragjain-git/text-classification
      run: python main.py
